blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/hypernym-studio/vscode-icons/discussions/new?category=ideas
    about: Suggest a new idea or a quick enhancement.
  - name: Questions & Help
    url: https://github.com/hypernym-studio/vscode-icons/discussions
    about: Please use Discussions for all additional questions or technical advices.
