export const fileExtensions = {
  html: 'html',
  vue: 'html',
  svelte: 'html',
  astro: 'html',
  jsx: 'html',
  tsx: 'html',
  css: 'style',
  postcss: 'style',
  scss: 'style',
  sass: 'style',
  less: 'style',
  stylus: 'style',
  json: 'json',
  jpg: 'image',
  jpeg: 'image',
  png: 'image',
  gif: 'image',
  webp: 'image',
  tiff: 'image',
  ico: 'image',
  svg: 'image',
  otf: 'font',
  ttf: 'font',
  woff: 'font',
  woff2: 'font'
}
